// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj-SRUYQuE6OH88A6TNqXbiYK53znWa5Y',
    appId: '1:301811027373:web:34913d353cf5282d22e524',
    messagingSenderId: '301811027373',
    projectId: 'toyproject-mypage',
    authDomain: 'toyproject-mypage.firebaseapp.com',
    storageBucket: 'toyproject-mypage.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkLPwJpqLHPgKKJgeic6XrpQVFuLhomYM',
    appId: '1:301811027373:android:c2290180eb4588eb22e524',
    messagingSenderId: '301811027373',
    projectId: 'toyproject-mypage',
    storageBucket: 'toyproject-mypage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5C8duNZQmQrLHl3X7gtAdXpFodm48TCM',
    appId: '1:301811027373:ios:87a17a1d4e13532b22e524',
    messagingSenderId: '301811027373',
    projectId: 'toyproject-mypage',
    storageBucket: 'toyproject-mypage.firebasestorage.app',
    iosBundleId: 'com.silso.silsoToyproject',
  );
}
